# Generated by Django 4.1.3 on 2022-12-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='group',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='weekly_class',
            new_name='student_numbers',
        ),
        migrations.RemoveField(
            model_name='school',
            name='location',
        ),
        migrations.RemoveField(
            model_name='school',
            name='ranking',
        ),
        migrations.RemoveField(
            model_name='school',
            name='student',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='student',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='trainer',
        ),
        migrations.AddField(
            model_name='school',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
