# Generated by Django 4.1.3 on 2022-12-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0003_subject_weekly_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.CharField(default='Rahima', max_length=100),
        ),
    ]
