# Generated by Django 4.1.3 on 2022-12-03 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0004_subject_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='teacher',
            new_name='trainer',
        ),
    ]
